package client.gui;

import client.Client;

import javax.swing.*;
import java.awt.*;

/**
 * @author rayquaza
 */
public class LoginFrame extends javax.swing.JFrame {

    private final Client client;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField loginField;
    // End of variables declaration//GEN-END:variables

    /**
     * Creates new form LoginFrame
     *
     * @param client current client
     */
    public LoginFrame(Client client) {
        this.client = client;
        initComponents();
    }

    public void throwError(String message) {
        JOptionPane.showMessageDialog(null, message, "ERROR", JOptionPane.ERROR_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginField = new javax.swing.JTextField();
        javax.swing.JPanel panel = new javax.swing.JPanel();
        javax.swing.JLabel header = new javax.swing.JLabel();
        javax.swing.JLabel subtitle = new javax.swing.JLabel();
        javax.swing.JButton loginButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(555, 250));

        setTitle("P2P File Transfer App");

        header.setText("LOGIN");

        subtitle.setText("Choose a nickname:");

        loginButton.setText("LOGIN");
        loginButton.addActionListener(this::loginButtonActionPerformed);

        loginField.addActionListener(this::actionPerformed);

        panel.add(header);
        panel.add(subtitle);
        panel.add(loginField);
        panel.add(loginButton);

        javax.swing.GroupLayout pLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(pLayout);
        pLayout.setHorizontalGroup(
                pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pLayout.createSequentialGroup()
                                .addGroup(pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(pLayout.createSequentialGroup()
                                                .addGap(213, 213, 213)
                                                .addComponent(header))
                                        .addGroup(pLayout.createSequentialGroup()
                                                .addGap(159, 159, 159)
                                                .addComponent(subtitle))
                                        .addGroup(pLayout.createSequentialGroup()
                                                .addGap(171, 171, 171)
                                                .addComponent(loginField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(pLayout.createSequentialGroup()
                                                .addGap(199, 199, 199)
                                                .addComponent(loginButton)))
                                .addContainerGap(177, Short.MAX_VALUE))
        );
        pLayout.setVerticalGroup(
                pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(header)
                                .addGap(18, 18, 18)
                                .addComponent(subtitle)
                                .addGap(18, 18, 18)
                                .addComponent(loginField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(loginButton)
                                .addContainerGap(42, Short.MAX_VALUE))
        );

        header.setBounds(195, 30, 300, 50);
        header.setFont(new Font("Verdana", Font.BOLD, 45));
        subtitle.setBounds(70, 90, 300, 30);
        subtitle.setFont(new Font("Verdana", Font.ITALIC, 15));
        loginField.setBounds(270, 90, 200, 35);
        loginField.setFont(new Font("Verdana", Font.PLAIN, 16));
        loginButton.setBounds(220, 145, 110, 40);
        loginButton.setFont(new Font("Verdana", Font.BOLD, 13));

        panel.setLayout(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );

        setBounds(0, 0, 555, 250);
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        login();
    }//GEN-LAST:event_loginButtonActionPerformed

    private void actionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionPerformed
        login();
    }//GEN-LAST:event_actionPerformed

    private void login() {
        if (loginField.getText().length() > 0) {
            String command = "login " + loginField.getText();
            client.writeCommand(command);
        } else {
            JOptionPane.showMessageDialog(null, "Please enter a nickname.", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }
}
